### ISSUE TITLE
Add wrapper for /orgaos endpoint

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#11]
# :brazil: Adicionar wrapper para o endpoint `/endpoint`

## Problem / Problema

:gb: The SDK doesn't support `/orgaos` endpoint

:brazil: O sdk ainda não possui suporte para o endpoint de órgãos `/orgaos`.

## Solution / Solução

:gb: Add the methods respecting the patterns, validations and available options for each endpoint:

:brazil: Adicione os métodos respeitando os padrões, validações e opções disponíveis para cada endpoint:

* getOrgaos - endpoint `/orgaos`
* getOrgao - endpoint `/orgaos/{id}`
* getOrgaoEventos - endpoint `/orgaos/{id}/eventos`
* getOrgaoMembros - endpoint `/orgaos/{id}/membros`
* getOrgaoVotacoes - endpoint `/orgaos/{id}/votacoes`

**Comment by tfbbueno** [comment]
Mandei um PR sobre essa issue :)
