### ISSUE TITLE
Add tests for the utils methods

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#3]
## From

Todo:
- [ ] Add tests for the utils files, it will be more reliable (but needs all the setup, maybe jest?)
- [X] Add all the other endpoints for deputados

_Originally posted by @kimuraz in https://github.com/AcompanhaLegis/sdk-dados-abertos-camara-js/pull/2#issuecomment-697971811_

## Description
The validations can be a little tricky with so many options, maybe add the tests to guarantee all (or most) cases.

**Comment by clockwerkz** [comment]
Is this issue still up for grabs? I'd like to contribute to it and can add jest/unit tests for your utils.js file..

**Comment by kimuraz** [comment]
@clockwerkz Thanks for you interest, specially on the current stage (very early) of the project!

You're welcomed to contribute. I'd like add that we also need to setup Jest on the project (including scripts on the `package.json` file). Let me know if you need any other detail, just tag me here and I'll reply asap.

**Comment by clockwerkz** [comment]
Sounds good, thanks!

**Comment by clockwerkz** [comment]
Hey @kimuraz just a quick head's up that I have jest set up and I'm starting to write up some tests. I started with the validateFormat function in the utils.js and I noticed that the function returns true if there isn't a match (or there is no provided argument):
`export const validateFormat = (format) => format ? ['json', 'xml'].includes(format) : true;`

Shouldn't this return false if format is not valid?

I'm writing up the test as expecting true for now, but I just thought I'd run that by you. :)

**Comment by clockwerkz** [comment]
Linking the PR #21

**Comment by BrunaNayara** [comment]
Sorry, I did not follow this issue and PR. 
Does #21 closes this issue completely?
If so, I will close this. If not, I will close this and open another one with any remaining tasks.

@clockwerkz e @kimuraz

**Comment by clockwerkz** [comment]
Yep, I believe so! The PR was merged into master. :) I thought by linking the PR it would auto close the issue..

**Comment by BrunaNayara** [comment]
Nice! I think it closes, but I think it did not link :/ 
I will close it manually, then.

Thanks :D
