### ISSUE TITLE
Parcel is deprecated, we need to change the bundler

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#44]
We need to change our bundler since parcel 1 is deprecated.

With the suggestion on #29 we could think about a more resourceful bundler, maybe webpack, rollup or maybe checkout parcel v2.

Suggestions are welcomed and once the decision is made we will accept the PR for this issue.

**Comment by kimuraz** [comment]
@void-hr any news about this one? I think it's kind of block for #29, if you don't have enough time, just let us know! :)

**Comment by void-hr** [comment]
@kimuraz  I have installed Webpack. Configuring is taking time (as I am new). I am trying to figure out what I am missing.

**Comment by kimuraz** [comment]
@void-hr ok, no problems! Let us know if you need any help, you can also open a draft PR to discuss more specific things

**Comment by kimuraz** [comment]
@void-hr I think once you have `webpack` in place and the `webpack.config.js` file, you just need to call it on the scripts `"build": "webpack"`, you might also need `webpack-cli` you can check the docs here: https://webpack.js.org/api/cli/
