### ISSUE TITLE
Add wrapper for /frentes

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#5]
# :brazil: Adicionar wrapper para o endpoint `/frentes`

## Problem / Problema

:gb: The SDK doesn't support `/frentes` endpoint

:brazil: O sdk ainda não possui suporte para o endpoint de frentes `/frentes`.

## Solution / Solução

:gb: Add the methods respecting the patterns, validations and available options for each endpoint:

:brazil: Adicione os métodos respeitando os padrões, validações e opções disponíveis para cada endpoint:

* getFrentes - endpoint: `/frentes`
* getFrente - endpoint: `/frentes/{id}`
* getFrenteMembros - endpoint `/frentes/{id}/membros`

**Comment by LeonardoCamargo31** [comment]
I would like to take this on!

**Comment by kimuraz** [comment]
@LeonardoCamargo31 go on!

**Comment by kimuraz** [comment]
Closed by https://github.com/AcompanhaLegis/sdk-dados-abertos-camara-js/pull/16
