### ISSUE TITLE
Add wrapper for /legislaturas endpoint

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#6]
# :brazil: Adicionar wrapper para o endpoint `/legislaturas`

## Problem / Problema

:gb: The SDK doesn't support `/legislaturas` endpoint

:brazil: O sdk ainda não possui suporte para o endpoint de legislaturas `/legislaturas`.

## Solution / Solução

:gb: Add the methods respecting the patterns, validations and available options for each endpoint:

:brazil: Adicione os métodos respeitando os padrões, validações e opções disponíveis para cada endpoint:

* getLegislaturas - endpoint: `/legislaturas`
* getLegislatura - endpoint: `/legislaturas/{id}`
* getLegislaturaMesa - endpoint `/legislaturas/{id}/mesa`

**Comment by alexandreab** [comment]
Issue solved by #28
