### ISSUE TITLE
Add wrapper for /partidos

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#7]
# :brazil: Adicionar wrapper para o endpoint `/partidos`

## Problem / Problema

:gb: The SDK doesn't support `/partidos` endpoint

:brazil: O sdk ainda não possui suporte para o endpoint de partidos `/partidos`.

## Solution / Solução

:gb: Add the methods respecting the patterns, validations and available options for each endpoint:

:brazil: Adicione os métodos respeitando os padrões, validações e opções disponíveis para cada endpoint:

* getPartidos - endpoint: `/partidos`
* getPartido - endpoint: `/partidos/{id}`
* getPartidoMembros - endpoint `/partidos/{id}/membros`

**Comment by rguzg** [comment]
Hey, can I work on this issue?

**Comment by kimuraz** [comment]
@rguzg Sure!

**Comment by rguzg** [comment]
Is there a reason why the imports don't have the .js extension? Because I couldn't get sample.js to work unless I added the extension to the imports

**Comment by kimuraz** [comment]
@rguzg Yeah, primarily the `.js` extension should only be mandatory if you're not in the browser (sample.js runs through `parcel` on an `HTML file`. Check:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import (about importing modules)
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export (about "creating" and exporting modules)
* https://github.com/nodejs/modules/issues/444 (I don't agree with the proposal tho, but the discussion are quite enlightening)

I need to highlight that the project is still a WIP and that the `sample.js` and the HTML file running it is not even close to the ideal, it was something I've made just to be sure that the data was being requested.

A next step, to fully support node, would be using a bundler properly configured. Sorry about that, but currently I think you won't be able to run the file directly using `node`... Maybe we can address your comment on a new issue to move forward and make improvements on these matters.

**Comment by rguzg** [comment]
Yeah, it may be a good idea to also support node. For now, I left the imports as they were before I forked the repository

**Comment by kimuraz** [comment]
Thanks for bring this up, I'll open an issue about it soon.
