### ISSUE TITLE
Add wrapper for /referencias

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/sdk-dados-abertos-camara-js#9]
# :brazil: Adicionar wrapper para o endpoint `/referencias`

## Problem / Problema

:gb: The SDK doesn't support `/referencias` endpoint

:brazil: O sdk ainda não possui suporte para o endpoint de referências `/referencias`.

## Solution / Solução

:gb: Add the methods respecting the patterns, validations and available options for each endpoint:

:brazil: Adicione os métodos respeitando os padrões, validações e opções disponíveis para cada endpoint:

* getRefDeputados - endpoint `/referencias/deputados`
* getRefSituacaoDeputado - endpoint `/referencias/deputados/codSituacao`
* getRefUfDeputados - endpoint `/referencias/deputados/siglaUF`
* getRefEventos - endpoint `/referencias/eventos`
* getRefSituacaoEvento - endpoint `/referencias/eventos/codSituacaoEvento`
* getRefTipoEvento - endpoint `/referencias/eventos/codTipoEvento`
* getRefOrgaos - endpoint `/referencias/orgaos`
* getRefSituacaoOrgao - endpoint `/referencias/orgaos/codSituacao`
* getRefTipoOrgao - endpoint `/referencias/orgaos/codTipoOrgao`
* getRefProposicoes - endpoint `/referencias/proposicoes`
* getRefSituacaoProposicao - endpoint `/referencias/proposicoes/codSituacao`
* getRefTemaProposicao - endpoint `/referencias/proposicoes/codTema`
* getRefTipoAutorProposicao - endpoint  `/referencias/proposicoes/codTipoAutor`
* getRefTipoTramitacao - endpoint `/referencias/proposicoes/codTipoTramitacao`
* getRefTipoProposicao - endpoint `/referencias/proposicoes/siglaTipo`
* getRefSituacaoDeputado -/referencias/situacoesDeputado
* getRefUfs - endpoint `/referencias/uf`

> :gb: Note: For the endpoints `/referencias/situacoes*` and `/referencias/tipos*`, they return the same data as some of the others endpoint, for example `/referencias/situacoesDeputado` = `/referencias/deputados/codSituacao`.
:brazil: Nota: Para os endpoints `/referencias/situacoes*` e `/referencias/tipos*`, eles retornam os mesmos dados de outros endpoints, por exemplo `/referencias/situacoesDeputado` = `/referencias/deputados/codSituacao`.

**Comment by tfbbueno** [comment]
É necessário implementar 2x para os endpoints que retornam os mesmos dados ou apenas 1 deles já é suficiente?

**Comment by kimuraz** [comment]
Solved by https://github.com/AcompanhaLegis/sdk-dados-abertos-camara-js/pull/26
